// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDljLgG2Kmb-zcZNwfPSt5TA_oXpVqcxZE',
    appId: '1:760756231594:web:b98b653ec89af6072a9fd3',
    messagingSenderId: '760756231594',
    projectId: 'flavor-2fae1',
    authDomain: 'flavor-2fae1.firebaseapp.com',
    storageBucket: 'flavor-2fae1.appspot.com',
    measurementId: 'G-X5JYDJB5W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvhp7m-qlUZZmoiMT47GOS-xzUIPYiq4',
    appId: '1:760756231594:android:14dcbe23b61cf8262a9fd3',
    messagingSenderId: '760756231594',
    projectId: 'flavor-2fae1',
    storageBucket: 'flavor-2fae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvggp8Rp0MB1CZZXwudU1h15v66UAetM4',
    appId: '1:760756231594:ios:28892349f3213d3d2a9fd3',
    messagingSenderId: '760756231594',
    projectId: 'flavor-2fae1',
    storageBucket: 'flavor-2fae1.appspot.com',
    iosBundleId: 'com.example.flavor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvggp8Rp0MB1CZZXwudU1h15v66UAetM4',
    appId: '1:760756231594:ios:28892349f3213d3d2a9fd3',
    messagingSenderId: '760756231594',
    projectId: 'flavor-2fae1',
    storageBucket: 'flavor-2fae1.appspot.com',
    iosBundleId: 'com.example.flavor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDljLgG2Kmb-zcZNwfPSt5TA_oXpVqcxZE',
    appId: '1:760756231594:web:10078f6f925c8e8c2a9fd3',
    messagingSenderId: '760756231594',
    projectId: 'flavor-2fae1',
    authDomain: 'flavor-2fae1.firebaseapp.com',
    storageBucket: 'flavor-2fae1.appspot.com',
    measurementId: 'G-YG90KBLJLY',
  );
}
